language: java
before_install:
- openssl aes-256-cbc -K $encrypted_a65cce263ea6_key -iv $encrypted_a65cce263ea6_iv
  -in cloudspanner-key.json.enc -out cloudspanner-key.json -d
- openssl aes-256-cbc -K $encrypted_804864587906_key -iv $encrypted_804864587906_iv
  -in cloudspanner-key.json.enc -out cloudspanner-key.json -d
